#!/usr/bin/env bash
# a Bash script that views Best School 10 times, rather for the 9th iteration, views Best School and then Hi on a new line.
count=0
while [ $count -lt 10 ]
do 
if [ $count -eq 9 ]
then
echo "Hi"
fi
echo "Best School"
((count++))
done
