#!/usr/bin/env bash
# Views the contents of the current directory in list format.
#   Only views the part of the name after the first dash. 

list=$(ls)
for i in $list; do
  echo "$i" | cut -d '-' -f2
done
